version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'
    reviewers:
      - 'ShawnGeorge03'
      - 'EkVid'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'dev'
    reviewers:
      - 'ShawnGeorge03'
      - 'EkVid'
