name: Format
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev, main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD Commit
        uses: actions/checkout@v4.0.0
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 'lts'

      - uses: pnpm/action-setup@v2.4.0
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run Prettier
        run: pnpm run format

      - name: Commit Format Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'style: 🎨 Formatted Code'
          branch: ${{ github.head_ref }}
